var json_Rakenteilla_8 = {
"type": "FeatureCollection",
"name": "Rakenteilla_8",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "fid": "1", "Yritys": "Pragmacharge Oy", "Nimi": "HaminaKotkan satama (Mussalo)", "Käyttövoima": "Sähkö", "Kapasiteetti": "1200 kW", "Teho kW": "400 kW", "SijaintiN": 6699748.1, "SijaintiE": 494071.5, "Tilanne": "Rakenteilla", "Kunta": "Kotka", "Lisätietoja1": "", "Lisätietoja2": "", "Lisätietoja3": "", "Linkki": "PragmaCharge rakentaa ja operoi latausasemaa raskaan liikenteen sähkökäyttöisille kuorma-autoille, Kotkan Mussalon satamassa.", "Osoite": "", "TEN-T": "", "Sijaitseeko latauskenttä korkeintaan kolmen kilometrin päässä vähintään kolmen kattavaan tieverkkoon kuuluvan maantien poistumisliittymästä?": null, "Lähde": "https://yle.fi/a/74-20079597", "Muistiinpanot": "", "field_19": "", "field_20": null }, "geometry": { "type": "Point", "coordinates": [ 26.89229825958747, 60.433971953948358 ] } },
{ "type": "Feature", "properties": { "fid": "2", "Yritys": "Scania Suomi Oy ", "Nimi": "", "Käyttövoima": "Sähkö", "Kapasiteetti": "", "Teho kW": "", "SijaintiN": 6767890.7, "SijaintiE": 564569.862, "Tilanne": "Rakenteilla", "Kunta": "Lappeenranta", "Lisätietoja1": "Toimintaan syksyllä 2025", "Lisätietoja2": "", "Lisätietoja3": "", "Linkki": "", "Osoite": "Myllymäenkatu 8 53550, Lappeenranta", "TEN-T": "", "Sijaitseeko latauskenttä korkeintaan kolmen kilometrin päässä vähintään kolmen kattavaan tieverkkoon kuuluvan maantien poistumisliittymästä?": null, "Lähde": "https://www.scania.com/fi/fi/home/about-scania/newsroom/news/Suomen-ensimmainen-ADR-hyvaksytty-sahkokayttoinen-Scania-kuorma-auto.html", "Muistiinpanot": "", "field_19": "", "field_20": null }, "geometry": { "type": "Point", "coordinates": [ 28.19540975648437, 61.040525744203421 ] } },
{ "type": "Feature", "properties": { "fid": "3", "Yritys": "PLUGIT FINLAND OY", "Nimi": "Lieto", "Käyttövoima": "Sähkö", "Kapasiteetti": "Vähintään 3600  kW", "Teho kW": "Vähintään 1MW", "SijaintiN": 6712807.5, "SijaintiE": 247085.9, "Tilanne": "Rakenteilla", "Kunta": "Lieto", "Lisätietoja1": "EV tukipäätös 2024", "Lisätietoja2": "Pisteiden määrä: 4x 1MW. Lisäksi tarjotaan 600 kW:n CCS-latausta. ", "Lisätietoja3": "423-428-65-2", "Linkki": "", "Osoite": "Avantin teollisuusalue", "TEN-T": "", "Sijaitseeko latauskenttä korkeintaan kolmen kilometrin päässä vähintään kolmen kattavaan tieverkkoon kuuluvan maantien poistumisliittymästä?": null, "Lähde": "https://plugit.fi/uutiset/plugit-tuo-suomeen-ensimmaisen-megawattiluokan-latausaseman-plugit-pro-dc-lieto-avataan-syyskuussa-2025/", "Muistiinpanot": "", "field_19": "", "field_20": null }, "geometry": { "type": "Point", "coordinates": [ 22.397467621215849, 60.471847181924588 ] } }
]
}
