var json_Toiminnassa_7 = {
"type": "FeatureCollection",
"name": "Toiminnassa_7",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:OGC:1.3:CRS84" } },
"features": [
{ "type": "Feature", "properties": { "fid": "21", "Yritys": "Neste Oyj", "Nimi": "Neste Lataus Truck Janakkala Linnatuuli Itä", "Käyttövoima": "Sähkö", "Kapasiteetti": "400 kW", "Teho kW": "400 kW", "SijaintiN": 6749050.2, "SijaintiE": 369562.5, "Tilanne": "Toiminnassa ", "Kunta": "Janakkala ", "Lisätietoja1": "", "Lisätietoja2": "Pisteiden lukumäärä 1", "Lisätietoja3": "", "Linkki": "https://asemat.neste.fi/neste-lataus-truck-janakkala-linnatuuli-ita", "Osoite": "Helsingintie 1426, 12400 Janakkala", "TEN-T": "", "Sijaitseeko latauskenttä korkeintaan kolmen kilometrin päässä vähintään kolmen kattavaan tieverkkoon kuuluvan maantien poistumisliittymästä?": null, "Lähde": "https://asemat.neste.fi/neste-lataus-truck-janakkala-linnatuuli-ita", "Muistiinpanot": "" }, "geometry": { "type": "Point", "coordinates": [ 24.598873080362946, 60.855231613859878 ] } },
{ "type": "Feature", "properties": { "fid": "22", "Yritys": "Neste Oyj", "Nimi": "Neste Lataus Truck Janakkala Linnatuuli Länsi", "Käyttövoima": "Sähkö", "Kapasiteetti": "400 kW", "Teho kW": "400 kW", "SijaintiN": 6748942.1, "SijaintiE": 369334.8, "Tilanne": "Toiminnassa ", "Kunta": "Janakkala ", "Lisätietoja1": "", "Lisätietoja2": "Pisteiden lukumäärä 1", "Lisätietoja3": "", "Linkki": "https://asemat.neste.fi/neste-lataus-truck-janakkala-linnatuuli-lansi", "Osoite": "Helsingintie 1426, 12400 Janakkala", "TEN-T": "", "Sijaitseeko latauskenttä korkeintaan kolmen kilometrin päässä vähintään kolmen kattavaan tieverkkoon kuuluvan maantien poistumisliittymästä?": null, "Lähde": "https://asemat.neste.fi/neste-lataus-truck-janakkala-linnatuuli-lansi", "Muistiinpanot": "" }, "geometry": { "type": "Point", "coordinates": [ 24.59475878401436, 60.854187067720723 ] } },
{ "type": "Feature", "properties": { "fid": "25", "Yritys": "PLUGIT FINLAND OY", "Nimi": "Ahola Transport - Naantali julkinen", "Käyttövoima": "Sähkö", "Kapasiteetti": "720 kW", "Teho kW": "360 kW", "SijaintiN": 6713671.9, "SijaintiE": 228818.2, "Tilanne": "Toiminnassa", "Kunta": "Naantali", "Lisätietoja1": "", "Lisätietoja2": "Ahola yhteistyökumppanina, pisteiden määrä 4", "Lisätietoja3": "", "Linkki": "https://plugit.fi/plugit-lataus-verkosto/", "Osoite": "Lisenssikatu 10, Naantali", "TEN-T": "", "Sijaitseeko latauskenttä korkeintaan kolmen kilometrin päässä vähintään kolmen kattavaan tieverkkoon kuuluvan maantien poistumisliittymästä?": null, "Lähde": "https://plugit.fi/plugit-lataus-verkosto/", "Muistiinpanot": "" }, "geometry": { "type": "Point", "coordinates": [ 22.065250088316866, 60.467717384714462 ] } },
{ "type": "Feature", "properties": { "fid": "26", "Yritys": "PLUGIT FINLAND OY", "Nimi": "Pro DC - Viinikka ", "Käyttövoima": "Sähkö", "Kapasiteetti": "720 kW", "Teho kW": "360 kW ", "SijaintiN": 6821288.1, "SijaintiE": 328379.8, "Tilanne": "Toiminnassa", "Kunta": "Tampere", "Lisätietoja1": "", "Lisätietoja2": "Pisteiden määrä 3", "Lisätietoja3": "", "Linkki": "https://plugit.fi/plugit-lataus-verkosto/", "Osoite": "Lempääläntie 10, Tampere ", "TEN-T": "", "Sijaitseeko latauskenttä korkeintaan kolmen kilometrin päässä vähintään kolmen kattavaan tieverkkoon kuuluvan maantien poistumisliittymästä?": null, "Lähde": "https://plugit.fi/plugit-lataus-verkosto/", "Muistiinpanot": "" }, "geometry": { "type": "Point", "coordinates": [ 23.776502518552803, 61.487096121830028 ] } }
]
}
